/* Generated by quant_nn.py (round8): the 64-128-64-4 symbol network in integers,
   window 28 bits before a symbol's first bit and 36 from it. */
#pragma once
#include <stdint.h>

#define P25_OS4_NN_PRE    28
#define P25_OS4_NN_POST   36
#define P25_OS4_NN_BITS   (P25_OS4_NN_PRE + P25_OS4_NN_POST)
#define P25_OS4_NN_CHUNK  4
#define P25_OS4_NN_CHUNKS (P25_OS4_NN_BITS / P25_OS4_NN_CHUNK)
#define P25_OS4_NN_H1     128
#define P25_OS4_NN_H2     64
#define P25_OS4_NN_R1     0   /* layer 1 activations >> this into int16 */
#define P25_OS4_NN_SHIFT2 1   /* dsps_dotprod_s16 shift for layer 2 */
#define P25_OS4_NN_SHIFT3 3   /* layer 3 dot products >> this into int32 */
#define P25_OS4_NN_S3     5.242880000e+05f   /* layer 3 results / this = logits */

extern const int16_t p25_os4_nn_t1[P25_OS4_NN_CHUNKS][1 << P25_OS4_NN_CHUNK][P25_OS4_NN_H1];
extern const int16_t p25_os4_nn_b1[P25_OS4_NN_H1];
extern const int16_t p25_os4_nn_w2t[P25_OS4_NN_H1][P25_OS4_NN_H2];
extern const int32_t p25_os4_nn_b2[P25_OS4_NN_H2];
extern const int16_t p25_os4_nn_w3[4][P25_OS4_NN_H2];
extern const int32_t p25_os4_nn_b3[4];
