from pathlib import Path
import sys
rows=Path(sys.argv[1]).read_text().splitlines()
def enc(d):
 r=d<<11
 for i in range(18,10,-1):
  if r&(1<<i): r^=0xc75<<(i-11)
 c=(d<<11)|r
 return (c<<1)|(c.bit_count()&1)
assert len(rows)==268, 'expected256 codewords and6 LC/burst pairs'
mismatches=sum(enc(i)!=int(rows[i],16)>>4 for i in range(256))
print('Golay mismatches:',mismatches)
assert mismatches==0
h=['/* Independently generated by unmodified MMDVM-Host encoders.', ' * Commit 590c531391dfd3146073afbc3956f70d42c62a46; see dmr_reference_vectors.md. */','#ifndef DMR_REFERENCE_VECTORS_H','#define DMR_REFERENCE_VECTORS_H','#include <stdint.h>','static const uint32_t dmr_reference_slot[256] = {']
for i in range(0,256,8):h.append('    '+', '.join('0x'+rows[j][:5]+'u' for j in range(i,i+8))+',')
h+=['};','static const struct { uint8_t lc[12]; uint8_t burst[33]; } dmr_reference_lc[] = {']
for i in range(256,len(rows),2):
 vals=lambda s:', '.join('0x'+s[j:j+2] for j in range(0,len(s),2))
 h+=['    {{'+vals(rows[i])+'},','     {'+vals(rows[i+1])+'}},']
h+=['};','#endif']
Path(sys.argv[2]).write_text('\n'.join(h)+'\n')


