"""Render the licensed source font at its final 24 px size (no bitmap scaling)."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

repo=Path(__file__).resolve().parents[1]
font=ImageFont.truetype(str(repo/'integrations/cell-lab/fonts/DejaVuSansMono-Bold.ttf'),24)
data=[]
glyphs=[]
for code in range(32,127):
    image=Image.new('L',(15,26))
    ImageDraw.Draw(image).text((0,20),chr(code),font=font,fill=255,anchor='ls')
    box=image.getbbox()
    if box is None:
        glyphs.append((len(data),0,0,0,0))
        continue
    x,y,right,bottom=box
    width,height=right-x,bottom-y
    glyphs.append((len(data),width,height,x,20-bottom))
    coverage=[(v*15+127)//255 for v in image.crop(box).tobytes()]
    if len(coverage)%2:coverage.append(0)
    data.extend((coverage[i]<<4)|coverage[i+1] for i in range(0,len(coverage),2))
text='''/* Generated by tools/gen_cell_font.py. Native 24 px DejaVu Sans Mono Bold.
 * Font copyright and license: integrations/cell-lab/fonts/LICENSE.txt. */
#include "ls_font.h"
static const ls_font_glyph_t dsc[95]={
'''+''.join('    {'+','.join(map(str,g))+'},\n' for g in glyphs)+'''};
static const uint8_t bitmap[]={
'''+''.join('    '+','.join(f'0x{b:02x}' for b in data[i:i+16])+',\n' for i in range(0,len(data),16))+'''};
const ls_font_t ls_font_mono_24={
    .dsc=dsc,.bitmap=bitmap,.bitmap_len=sizeof(bitmap),.first=0x20,.count=95,
    .cell_w=15,.cell_h=26,.base_line=6,.name="ls_font_mono_24"
};
'''
(repo/'components/apps/tui/ls_font_mono_24.c').write_text(text)
print(f'Generated native 15x26 face: {len(data)} bytes, 95 glyphs')
