# Keep app_desc identity independent of tags, branch names and shell quoting.
function(ls_identity_format output product revision state)
    string(LENGTH "${product}" product_length)
    if(NOT "${product}" MATCHES "^[0-9]+(\\.[0-9]+)*$" OR product_length GREATER 10)
        set(product "0")
    endif()
    string(LENGTH "${revision}" revision_length)
    if("${state}" STREQUAL "archive")
        set(identity "${product}-archive")
    elseif(("${state}" STREQUAL "clean" OR "${state}" STREQUAL "dirty") AND
           "${revision}" MATCHES "^[0-9a-fA-F]+$" AND
           (revision_length EQUAL 40 OR revision_length EQUAL 64))
        string(SUBSTRING "${revision}" 0 12 short_revision)
        string(TOLOWER "${short_revision}" short_revision)
        set(identity "${product}-g${short_revision}")
        if("${state}" STREQUAL "dirty")
            string(APPEND identity "-dirty")
        endif()
    else()
        set(identity "${product}-unknown")
    endif()
    string(LENGTH "${identity}" identity_length)
    if(identity_length GREATER 31)
        message(FATAL_ERROR "LakeShark build identity exceeds app_desc capacity")
    endif()
    set(${output} "${identity}" PARENT_SCOPE)
endfunction()

function(ls_identity_write_metadata destination identity)
    if(NOT EXISTS "${destination}")
        return()
    endif()
    if(NOT "${identity}" MATCHES "^[0-9a-z.-]+$")
        message(FATAL_ERROR "Invalid build identity characters")
    endif()
    file(READ "${destination}" previous)
    set(pattern "\"project_version\"[ \t\r\n]*:[ \t\r\n]*\"[^\"\r\n]*\"")
    string(REGEX MATCHALL "${pattern}" matches "${previous}")
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Project metadata must contain exactly one project_version")
    endif()
    string(REGEX REPLACE "${pattern}" "\"project_version\": \"${identity}\"" content "${previous}")
    if(NOT "${previous}" STREQUAL "${content}")
        file(WRITE "${destination}" "${content}")
    endif()
endfunction()

function(ls_identity_query output source product)
    set(state "archive")
    set(revision "")
    # A source archive nested inside another checkout must not borrow its HEAD.
    # Both regular repositories and linked worktrees have this explicit entry.
    if(EXISTS "${source}/.git")
        set(state "unknown")
        if(NOT GIT_EXECUTABLE)
            find_program(GIT_EXECUTABLE NAMES git)
        endif()
        if(GIT_EXECUTABLE)
            execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" rev-parse --verify HEAD
                RESULT_VARIABLE revision_result OUTPUT_VARIABLE revision
                OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET TIMEOUT 10)
            if("${revision_result}" STREQUAL "0")
                execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}"
                    status --porcelain=v1 --untracked-files=normal --ignore-submodules=none
                    RESULT_VARIABLE status_result OUTPUT_VARIABLE status
                    ERROR_QUIET TIMEOUT 10)
                if("${status_result}" STREQUAL "0")
                    if("${status}" STREQUAL "")
                        set(state "clean")
                    else()
                        set(state "dirty")
                    endif()
                endif()
            endif()
        endif()
    endif()
    ls_identity_format(identity "${product}" "${revision}" "${state}")
    set(${output} "${identity}" PARENT_SCOPE)
endfunction()

function(ls_identity_write_header destination identity)
    # Only the formatter's restricted alphabet is admitted into a C definition.
    if(NOT "${identity}" MATCHES "^[0-9a-z.-]+$")
        message(FATAL_ERROR "Invalid build identity characters")
    endif()
    set(content "/* Generated build identity: do not edit. */\n#ifndef LS_BUILD_IDENTITY_H\n#define LS_BUILD_IDENTITY_H\n#ifdef PROJECT_VER\n#undef PROJECT_VER\n#endif\n#define PROJECT_VER \"${identity}\"\n#endif\n")
    if(EXISTS "${destination}")
        file(READ "${destination}" previous)
        if("${previous}" STREQUAL "${content}")
            return()
        endif()
    endif()
    get_filename_component(directory "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${destination}" "${content}")
endfunction()
