#ifndef LS_TEST_HOSTED_PORT_CONFIG_H
#define LS_TEST_HOSTED_PORT_CONFIG_H
#define H_USE_MEMPOOL 1
#define H_TRANSPORT_NONE 0
#define H_TRANSPORT_SDIO 1
#define H_TRANSPORT_SPI_HD 2
#define H_TRANSPORT_SPI 3
#define H_TRANSPORT_UART 4
#define H_TRANSPORT_IN_USE H_TRANSPORT_SDIO
#define CONFIG_ESP_HOSTED_GPIO_SLAVE_RESET_SLAVE 54
#endif
