"""Generate a coarse land mask from original approximate continent outlines."""
from pathlib import Path
polygons = [
    [(-168,70),(-140,70),(-125,58),(-108,70),(-80,62),(-52,50),(-65,44),(-82,25),(-98,16),(-111,29),(-128,49),(-165,58)],
    [(-82,12),(-63,10),(-35,-6),(-43,-24),(-56,-55),(-72,-48),(-79,-10)],
    [(-52,83),(-22,78),(-40,60),(-58,65)],
    [(-11,36),(-11,58),(9,72),(40,69),(60,78),(110,72),(170,66),(179,50),(145,42),(126,30),(110,1),(100,8),(79,8),(65,25),(43,12),(35,31),(12,36)],
    [(-17,32),(9,37),(34,30),(51,11),(40,-10),(32,-34),(18,-35),(10,-5),(-14,10)],
    [(112,-12),(136,-11),(154,-25),(146,-40),(116,-35)],
    [(47,-13),(51,-16),(48,-26),(44,-24)],
    [(166,-35),(178,-38),(172,-47),(165,-44)],
    [(96,3),(120,1),(131,-7),(110,-9)],
    [(-180,-75),(180,-75),(180,-90),(-180,-90)],
]
def inside(x,y,poly):
    odd=False
    for i,(ax,ay) in enumerate(poly):
        bx,by=poly[i-1]
        if (ay>y)!=(by>y) and x<(bx-ax)*(y-ay)/(by-ay)+ax:
            odd=not odd
    return odd
rows=[]
for y in range(36):
    bits=[0]*9
    for x in range(72):
        if any(inside(-177.5+x*5,87.5-y*5,p) for p in polygons): bits[x//8]|=1<<(x%8)
    rows.append('    {'+','.join(f'0x{b:02x}' for b in bits)+'},')
Path('components/apps/tui/ls_tiles_world.h').write_text('/* Generated by bench/tools/tiles_world.py; coarse original land mask. */\nstatic const unsigned char tiles_world[36][9]={\n'+'\n'.join(rows)+'\n};\n')
